framework:
  messenger:
    transports:
      sync: 'sync://'

    routing:
      'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
      # Si tu as des messages maison pour tes mails, ajoute-les aussi :
      # 'App\Message\ContactMessage': sync
      # 'App\Message\ReviewMessage':  sync
