name: Symfony CI/CD

on:
    push:
        branches: ["main"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                    MYSQL_USER: test
                    MYSQL_PASSWORD: test
                ports: 
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

            mailhog:
                image: mailhog/mailhog
                ports:
                - "1025:1025"
                - "8025:8025"

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'
                extensions: mbstring, xml, pdo_mysql, intl, zip
                tools: composer:v2

            - name: Cache Composer packages
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

            - name: Run Symfony auto-scripts
              run: composer run-script auto-scripts
              env:
                APP_ENV: test

            - name: Clear cache
              run: php bin/console cache:clear --env=test

            - name: Set DATABASE_URL for tests
              run: echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/test" >> $GITHUB_ENV

            - name: Run tests
              run: php bin/phpunit --testdox
    
    docker-build-push:
        runs-on: ubuntu-latest
        needs: build-and-test

        steps:
            - uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.USER_NAME}}
                password: ${{secrets.PASSWORD}}

            - name: Build Docker image
              run: docker build -t naelle69/coach-site:latest .

            - name: Push Docker image
              run: docker push naelle69/coach-site:latest